language: python
python:
  - "2.7"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install: "sudo apt-get install -y -f python python-dev python-pip pkg-config python-wxgtk2.8 libpng-dev libjpeg8-dev libfreetype6-dev"
      install: "pip install --upgrade pip setuptools numpy scipy pillow matplotlib pytest"
    - os: osx
      before_install: "git clone https://github.com/MacPython/terryfy && source terryfy/travis_tools.sh && get_python_environment  macpython 2.7.10"
      brew_packages: "python-pip"
      install: "pip install --upgrade pip setuptools numpy scipy pillow matplotlib pytest"
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew install python-pip
        - git clone https://github.com/MacPython/terryfy
        - source terryfy/travis_tools.sh
        - get_python_environment  macpython 2.7.10
      install:
        - pip install --upgrade pip setuptools numpy scipy pillow matplotlib pytest


DISPLAY: 0.0
notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
before_script: cd /home/travis/build/mad-lab/transit/tests
script: travis_wait 30 pytest
