language: python

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      python: 2.7
      before_install: "sudo apt-get install -y -f python2.7 python-dev python-pip pkg-config libpng-dev libjpeg8-dev libfreetype6-dev r-base"
      install: "pip install --upgrade pip setuptools numpy scipy pillow matplotlib pytest statsmodels 'rpy2<2.9.0'"

DISPLAY: 0.0
notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
before_script: cd /home/travis/build/mad-lab/transit/tests
script: travis_wait 30 pytest
